name: Print Secrets Workflow
on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Secrets
        run: |
          echo "Secrets:"
          echo "SECRET_KEY: ${{ secrets.API_KEY }}"
